apiVersion: batch/v1
kind: Job
metadata:
  name: copy-utils
  namespace: witcash
spec:
  template:
    spec:
      containers:
      - image: gcr.io/k8switcash/copy-utils:v1.1
        name: copy-utils
        command: ["sh","-c","gsutil -m cp -r gs://nbxplorer/* /data/pvc"]
        volumeMounts:
        - name: pvc
          mountPath: /data/pvc
      restartPolicy: Never
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: mypvc-test