apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcore-pvc
  namespace: witcash
  labels:
    app: bitcore
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: witcash-node
  namespace: witcash
  annotations:
    kubernetes.io/change-cause: "first commit"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: witcash-node
  template:
    metadata:
      labels:
        run: witcash-node
    spec:
      imagePullSecrets:
      - name: bitcore-docker-secret

      containers:
      - name: bitcore
        image: witcashnode/bitcoincore:bitcore
        ports:
        - containerPort: 2332
          protocol: TCP
        volumeMounts:
        - name: witcash-node-persistent-storage
          mountPath: /bitcoin/data
          subPath: bitcoin_data

      - name: nbxplorer
        image: witcashnode/bitcoincore:nbxplorer
        ports:
        - containerPort: 24444
          protocol: TCP
        volumeMounts:
        - name: witcash-node-persistent-storage
          mountPath: /NBXplorer/data
          subPath: nbxplorer_data

      volumes:
      - name: witcash-node-persistent-storage
        persistentVolumeClaim:
          claimName: bitcore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: witcash-node
  namespace: witcash
spec:
  selector:
    run: witcash-node

  ports:
    - name: witcash-node
      targetPort: 24444
      port: 24444

  type: LoadBalancer