apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: witcash
configMapGenerator:
- name: bitcore-configmap 
  files:
  - bitcoin.conf
- name: nbxplorer-configmap
  files:
  - settings.config

# kubectl apply -k .