apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbxplorer-pvc
  namespace: witcash
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: csi-cephfs-storageclass