apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: witcash-node
  namespace: witcash
spec:
  serviceName: witpay
  replicas: 2
  selector:
    matchLabels:
      run: witcash-node
  template:
    metadata:
      labels:
        run: witcash-node
    spec:
      imagePullSecrets:
      - name: bitcore-docker-secret

      containers:
      - name: bitcore
        image: witcashnode/bitcoincore:bitcore
        ports:
        - containerPort: 2332
          protocol: TCP
        volumeMounts:
        - name: witcash-node-persistent-storage
          mountPath: /bitcoin/data
          subPath: bitcoin_data

      - name: nbxplorer
        image: witcashnode/bitcoincore:nbxplorer
        ports:
        - containerPort: 24444
          protocol: TCP
        volumeMounts:
        - name: witcash-node-persistent-storage
          mountPath: /NBXplorer/data
          subPath: nbxplorer_data

   volumeClaimTemplates:
   - metadata:
       name: witcash-node-persistent-storage
     spec:
       accessModes: [ "ReadWriteOnce" ]
       storageClassName: "standard"
       resources:
         requests:
           storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: witcash-node
  namespace: witcash
spec:
  type: LoadBalancer
  selector:
    run: witcash-node

  ports:
    - name: witcash-node
      targetPort: 24444
      port: 24444




